### PR TITLE
DON'T MERGE: Configurable API Actions

### PR DESCRIPTION
**Pull request by dmdez**
Added helper function to create api config and to create api request object to be injected into redux middleware, set up some examples on the corps load/create actions as well as the corpse reducer

### CODE REVIEW

**Review by roblafeve — COMMENTED** [review]
@dmdez Do you need any help implementing the changes we talked about or converting the current request actions?

**Comment by roblafeve** [comment]
@dmdez @albatrocity you guys mind closing this PR—just trying to clean up what shows in my PR mentions 😆

**Comment by ChrisWphoto** [comment]
Throw back for realsies! :D

**Comment by albatrocity** [comment]
@roblafeve I don't have write access anymore. @dmdez are you able to close this?

**Comment by dmdez** [comment]
😢 😭 😿

**Comment by roblafeve** [comment]
😢

**Pull request closed without merging**
